// Beginner Spanish curriculum data.
// Each lesson has an id, title, emoji icon, short description, and a word/phrase list.
// `pron` is a simplified, non-IPA pronunciation hint aimed at English speakers.

const LESSONS = [
  {
    id: "greetings",
    title: "Greetings & Courtesy",
    icon: "👋",
    description: "Say hello, goodbye, and be polite.",
    words: [
      { es: "Hola", en: "Hello", pron: "OH-lah" },
      { es: "Adiós", en: "Goodbye", pron: "ah-DYOHS" },
      { es: "Buenos días", en: "Good morning", pron: "BWEH-nohs DEE-ahs" },
      { es: "Buenas tardes", en: "Good afternoon", pron: "BWEH-nahs TAR-dehs" },
      { es: "Buenas noches", en: "Good evening / night", pron: "BWEH-nahs NOH-chehs" },
      { es: "Por favor", en: "Please", pron: "por fah-VOR" },
      { es: "Gracias", en: "Thank you", pron: "GRAH-syahs" },
      { es: "De nada", en: "You're welcome", pron: "deh NAH-dah" },
      { es: "Lo siento", en: "I'm sorry", pron: "loh SYEN-toh" },
      { es: "Perdón", en: "Excuse me / Pardon", pron: "per-DOHN" },
      { es: "Sí", en: "Yes", pron: "see" },
      { es: "No", en: "No", pron: "noh" },
      { es: "Mucho gusto", en: "Nice to meet you", pron: "MOO-choh GOOS-toh" },
      { es: "¿Cómo estás?", en: "How are you?", pron: "KOH-moh ehs-TAHS" },
      { es: "Bien, gracias", en: "Fine, thank you", pron: "byen GRAH-syahs" },
    ],
  },
  {
    id: "numbers",
    title: "Numbers 0-20",
    icon: "🔢",
    description: "Count from zero to twenty.",
    words: [
      { es: "cero", en: "zero", pron: "SEH-roh" },
      { es: "uno", en: "one", pron: "OO-noh" },
      { es: "dos", en: "two", pron: "dohs" },
      { es: "tres", en: "three", pron: "trehs" },
      { es: "cuatro", en: "four", pron: "KWAH-troh" },
      { es: "cinco", en: "five", pron: "SEEN-koh" },
      { es: "seis", en: "six", pron: "SEH-ees" },
      { es: "siete", en: "seven", pron: "SYEH-teh" },
      { es: "ocho", en: "eight", pron: "OH-choh" },
      { es: "nueve", en: "nine", pron: "NWEH-veh" },
      { es: "diez", en: "ten", pron: "dyehs" },
      { es: "once", en: "eleven", pron: "OHN-seh" },
      { es: "doce", en: "twelve", pron: "DOH-seh" },
      { es: "trece", en: "thirteen", pron: "TREH-seh" },
      { es: "catorce", en: "fourteen", pron: "kah-TOR-seh" },
      { es: "quince", en: "fifteen", pron: "KEEN-seh" },
      { es: "veinte", en: "twenty", pron: "VAIN-teh" },
    ],
  },
  {
    id: "numbers-20-40",
    title: "Numbers 20-40",
    icon: "🧮",
    description: "Count from twenty to forty.",
    words: [
      { es: "veinte", en: "twenty", pron: "VAIN-teh" },
      { es: "veintiuno", en: "twenty-one", pron: "vain-tee-OO-noh" },
      { es: "veintidós", en: "twenty-two", pron: "vain-tee-DOHS" },
      { es: "veintitrés", en: "twenty-three", pron: "vain-tee-TREHS" },
      { es: "veinticuatro", en: "twenty-four", pron: "vain-tee-KWAH-troh" },
      { es: "veinticinco", en: "twenty-five", pron: "vain-tee-SEEN-koh" },
      { es: "veintiséis", en: "twenty-six", pron: "vain-tee-SEH-ees" },
      { es: "veintisiete", en: "twenty-seven", pron: "vain-tee-SYEH-teh" },
      { es: "veintiocho", en: "twenty-eight", pron: "vain-tee-OH-choh" },
      { es: "veintinueve", en: "twenty-nine", pron: "vain-tee-NWEH-veh" },
      { es: "treinta", en: "thirty", pron: "TRAIN-tah" },
      { es: "treinta y uno", en: "thirty-one", pron: "TRAIN-tah ee OO-noh" },
      { es: "treinta y dos", en: "thirty-two", pron: "TRAIN-tah ee DOHS" },
      { es: "treinta y tres", en: "thirty-three", pron: "TRAIN-tah ee TREHS" },
      { es: "treinta y cuatro", en: "thirty-four", pron: "TRAIN-tah ee KWAH-troh" },
      { es: "treinta y cinco", en: "thirty-five", pron: "TRAIN-tah ee SEEN-koh" },
      { es: "treinta y seis", en: "thirty-six", pron: "TRAIN-tah ee SEH-ees" },
      { es: "treinta y siete", en: "thirty-seven", pron: "TRAIN-tah ee SYEH-teh" },
      { es: "treinta y ocho", en: "thirty-eight", pron: "TRAIN-tah ee OH-choh" },
      { es: "treinta y nueve", en: "thirty-nine", pron: "TRAIN-tah ee NWEH-veh" },
      { es: "cuarenta", en: "forty", pron: "kwah-REHN-tah" },
    ],
  },
  {
    id: "numbers-40-60",
    title: "Numbers 40-60",
    icon: "🔟",
    description: "Count from forty to sixty.",
    words: [
      { es: "cuarenta", en: "forty", pron: "kwah-REHN-tah" },
      { es: "cuarenta y uno", en: "forty-one", pron: "kwah-REHN-tah ee OO-noh" },
      { es: "cuarenta y dos", en: "forty-two", pron: "kwah-REHN-tah ee DOHS" },
      { es: "cuarenta y tres", en: "forty-three", pron: "kwah-REHN-tah ee TREHS" },
      { es: "cuarenta y cuatro", en: "forty-four", pron: "kwah-REHN-tah ee KWAH-troh" },
      { es: "cuarenta y cinco", en: "forty-five", pron: "kwah-REHN-tah ee SEEN-koh" },
      { es: "cuarenta y seis", en: "forty-six", pron: "kwah-REHN-tah ee SEH-ees" },
      { es: "cuarenta y siete", en: "forty-seven", pron: "kwah-REHN-tah ee SYEH-teh" },
      { es: "cuarenta y ocho", en: "forty-eight", pron: "kwah-REHN-tah ee OH-choh" },
      { es: "cuarenta y nueve", en: "forty-nine", pron: "kwah-REHN-tah ee NWEH-veh" },
      { es: "cincuenta", en: "fifty", pron: "seen-KWEHN-tah" },
      { es: "cincuenta y uno", en: "fifty-one", pron: "seen-KWEHN-tah ee OO-noh" },
      { es: "cincuenta y dos", en: "fifty-two", pron: "seen-KWEHN-tah ee DOHS" },
      { es: "cincuenta y tres", en: "fifty-three", pron: "seen-KWEHN-tah ee TREHS" },
      { es: "cincuenta y cuatro", en: "fifty-four", pron: "seen-KWEHN-tah ee KWAH-troh" },
      { es: "cincuenta y cinco", en: "fifty-five", pron: "seen-KWEHN-tah ee SEEN-koh" },
      { es: "cincuenta y seis", en: "fifty-six", pron: "seen-KWEHN-tah ee SEH-ees" },
      { es: "cincuenta y siete", en: "fifty-seven", pron: "seen-KWEHN-tah ee SYEH-teh" },
      { es: "cincuenta y ocho", en: "fifty-eight", pron: "seen-KWEHN-tah ee OH-choh" },
      { es: "cincuenta y nueve", en: "fifty-nine", pron: "seen-KWEHN-tah ee NWEH-veh" },
      { es: "sesenta", en: "sixty", pron: "seh-SEHN-tah" },
    ],
  },
  {
    id: "colors",
    title: "Colors",
    icon: "🎨",
    description: "Describe the world around you.",
    words: [
      { es: "rojo", en: "red", pron: "ROH-hoh" },
      { es: "azul", en: "blue", pron: "ah-SOOL" },
      { es: "verde", en: "green", pron: "VER-deh" },
      { es: "amarillo", en: "yellow", pron: "ah-mah-REE-yoh" },
      { es: "naranja", en: "orange", pron: "nah-RAHN-hah" },
      { es: "morado", en: "purple", pron: "moh-RAH-doh" },
      { es: "rosa", en: "pink", pron: "ROH-sah" },
      { es: "negro", en: "black", pron: "NEH-groh" },
      { es: "blanco", en: "white", pron: "BLAHN-koh" },
      { es: "gris", en: "gray", pron: "grees" },
      { es: "marrón", en: "brown", pron: "mah-ROHN" },
    ],
  },
  {
    id: "days",
    title: "Days & Months",
    icon: "📅",
    description: "Talk about the calendar.",
    words: [
      { es: "lunes", en: "Monday", pron: "LOO-nehs" },
      { es: "martes", en: "Tuesday", pron: "MAR-tehs" },
      { es: "miércoles", en: "Wednesday", pron: "MYEHR-koh-lehs" },
      { es: "jueves", en: "Thursday", pron: "HWEH-vehs" },
      { es: "viernes", en: "Friday", pron: "VYEHR-nehs" },
      { es: "sábado", en: "Saturday", pron: "SAH-bah-doh" },
      { es: "domingo", en: "Sunday", pron: "doh-MEEN-goh" },
      { es: "enero", en: "January", pron: "eh-NEH-roh" },
      { es: "febrero", en: "February", pron: "feh-BREH-roh" },
      { es: "marzo", en: "March", pron: "MAR-soh" },
      { es: "abril", en: "April", pron: "ah-BREEL" },
      { es: "mayo", en: "May", pron: "MAH-yoh" },
      { es: "junio", en: "June", pron: "HOO-nyoh" },
      { es: "julio", en: "July", pron: "HOO-lyoh" },
      { es: "agosto", en: "August", pron: "ah-GOHS-toh" },
      { es: "septiembre", en: "September", pron: "sep-TYEM-breh" },
      { es: "octubre", en: "October", pron: "ok-TOO-breh" },
      { es: "noviembre", en: "November", pron: "noh-VYEM-breh" },
      { es: "diciembre", en: "December", pron: "dee-SYEM-breh" },
      { es: "hoy", en: "today", pron: "oy" },
      { es: "mañana", en: "tomorrow", pron: "mah-NYAH-nah" },
      { es: "pasado mañana", en: "the day after tomorrow", pron: "pah-SAH-doh mah-NYAH-nah" },
      { es: "ayer", en: "yesterday", pron: "ah-YEHR" },
      { es: "anteayer", en: "the day before yesterday", pron: "ahn-teh-ah-YEHR" },
    ],
  },
  {
    id: "family",
    title: "Family",
    icon: "👪",
    description: "Meet the family members.",
    words: [
      { es: "la familia", en: "the family", pron: "lah fah-MEE-lyah" },
      { es: "la madre", en: "mother", pron: "lah MAH-dreh" },
      { es: "el padre", en: "father", pron: "el PAH-dreh" },
      { es: "el hermano", en: "brother", pron: "el er-MAH-noh" },
      { es: "la hermana", en: "sister", pron: "lah er-MAH-nah" },
      { es: "el hijo", en: "son", pron: "el EE-hoh" },
      { es: "la hija", en: "daughter", pron: "lah EE-hah" },
      { es: "el abuelo", en: "grandfather", pron: "el ah-BWEH-loh" },
      { es: "la abuela", en: "grandmother", pron: "lah ah-BWEH-lah" },
      { es: "el esposo", en: "husband", pron: "el ehs-POH-soh" },
      { es: "la esposa", en: "wife", pron: "lah ehs-POH-sah" },
      { es: "el amigo", en: "friend (male)", pron: "el ah-MEE-goh" },
      { es: "la amiga", en: "friend (female)", pron: "lah ah-MEE-gah" },
    ],
  },
  {
    id: "questions",
    title: "Common Questions",
    icon: "❓",
    description: "Ask about names, origin, and more.",
    words: [
      { es: "¿Cómo te llamas?", en: "What is your name?", pron: "KOH-moh teh YAH-mahs" },
      { es: "Me llamo...", en: "My name is...", pron: "meh YAH-moh" },
      { es: "¿De dónde eres?", en: "Where are you from?", pron: "deh DOHN-deh EH-rehs" },
      { es: "Soy de...", en: "I am from...", pron: "soy deh" },
      { es: "¿Qué hora es?", en: "What time is it?", pron: "keh OH-rah ehs" },
      { es: "¿Dónde está...?", en: "Where is...?", pron: "DOHN-deh ehs-TAH" },
      { es: "¿Cuánto cuesta?", en: "How much does it cost?", pron: "KWAN-toh KWEHS-tah" },
      { es: "¿Qué es esto?", en: "What is this?", pron: "keh ehs EHS-toh" },
      { es: "¿Puedes ayudarme?", en: "Can you help me?", pron: "PWEH-dehs ah-yoo-DAR-meh" },
      { es: "No entiendo", en: "I don't understand", pron: "noh en-TYEN-doh" },
    ],
  },
  {
    id: "food",
    title: "Food & Drink",
    icon: "🍽️",
    description: "Order and talk about meals.",
    words: [
      { es: "el agua", en: "water", pron: "el AH-gwah" },
      { es: "el café", en: "coffee", pron: "el kah-FEH" },
      { es: "el pan", en: "bread", pron: "el pahn" },
      { es: "el queso", en: "cheese", pron: "el KEH-soh" },
      { es: "la fruta", en: "fruit", pron: "lah FROO-tah" },
      { es: "la manzana", en: "apple", pron: "lah mahn-SAH-nah" },
      { es: "el pollo", en: "chicken", pron: "el POH-yoh" },
      { es: "el arroz", en: "rice", pron: "el ah-ROHS" },
      { es: "la leche", en: "milk", pron: "lah LEH-cheh" },
      { es: "el desayuno", en: "breakfast", pron: "el deh-sah-YOO-noh" },
      { es: "el almuerzo", en: "lunch", pron: "el ahl-MWEHR-soh" },
      { es: "la cena", en: "dinner", pron: "lah SEH-nah" },
      { es: "Tengo hambre", en: "I am hungry", pron: "TEHN-goh AHM-breh" },
      { es: "Tengo sed", en: "I am thirsty", pron: "TEHN-goh sehd" },
    ],
  },
  {
    id: "verbs",
    title: "Ser vs. Estar",
    icon: "🔤",
    description: "The two verbs for 'to be' (present tense).",
    words: [
      { es: "yo soy", en: "I am (ser - identity)", pron: "yoh soy" },
      { es: "tú eres", en: "you are (ser - identity)", pron: "too EH-rehs" },
      { es: "él/ella es", en: "he/she is (ser - identity)", pron: "el EH-yah ehs" },
      { es: "nosotros somos", en: "we are (ser - identity)", pron: "noh-SOH-trohs SOH-mohs" },
      { es: "yo estoy", en: "I am (estar - state/location)", pron: "yoh ehs-TOY" },
      { es: "tú estás", en: "you are (estar - state/location)", pron: "too ehs-TAHS" },
      { es: "él/ella está", en: "he/she is (estar - state/location)", pron: "el EH-yah ehs-TAH" },
      { es: "nosotros estamos", en: "we are (estar - state/location)", pron: "noh-SOH-trohs ehs-TAH-mohs" },
      { es: "Soy alto", en: "I am tall (permanent trait)", pron: "soy AHL-toh" },
      { es: "Estoy cansado", en: "I am tired (temporary state)", pron: "ehs-TOY kahn-SAH-doh" },
    ],
  },
];
