// Beginner Spanish curriculum data.
// Each lesson has an id, title, an icon (SVG markup referencing a symbol in index.html's
// sprite), short description, and a word/phrase list.
// `pron` is a simplified, non-IPA pronunciation hint aimed at English speakers.

const LESSONS = [
  {
    id: "greetings",
    title: "Greetings & Courtesy",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-wave\"></use></svg>",
    description: "Say hello, goodbye, and be polite.",
    words: [
      { es: "Hola", en: "Hello", pron: "OH-lah" },
      { es: "Adiós", en: "Goodbye", pron: "ah-DYOHS" },
      { es: "Buenos días", en: "Good morning", pron: "BWEH-nohs DEE-ahs" },
      { es: "Buenas tardes", en: "Good afternoon", pron: "BWEH-nahs TAR-dehs" },
      { es: "Buenas noches", en: "Good evening / night", pron: "BWEH-nahs NOH-chehs" },
      { es: "Por favor", en: "Please", pron: "por fah-VOR" },
      { es: "Gracias", en: "Thank you", pron: "GRAH-syahs" },
      { es: "De nada", en: "You're welcome", pron: "deh NAH-dah" },
      { es: "Lo siento", en: "I'm sorry", pron: "loh SYEN-toh" },
      { es: "Perdón", en: "Excuse me / Pardon", pron: "per-DOHN" },
      { es: "Sí", en: "Yes", pron: "see" },
      { es: "No", en: "No", pron: "noh" },
      { es: "Mucho gusto", en: "Nice to meet you", pron: "MOO-choh GOOS-toh" },
      { es: "¿Cómo estás?", en: "How are you?", pron: "KOH-moh ehs-TAHS" },
      { es: "Bien, gracias", en: "Fine, thank you", pron: "byen GRAH-syahs" },
    ],
  },
  {
    id: "numbers",
    title: "Numbers 0-20",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-numbers\"></use></svg>",
    description: "Count from zero to twenty.",
    words: [
      { es: "cero", en: "zero", pron: "SEH-roh" },
      { es: "uno", en: "one", pron: "OO-noh" },
      { es: "dos", en: "two", pron: "dohs" },
      { es: "tres", en: "three", pron: "trehs" },
      { es: "cuatro", en: "four", pron: "KWAH-troh" },
      { es: "cinco", en: "five", pron: "SEEN-koh" },
      { es: "seis", en: "six", pron: "SEH-ees" },
      { es: "siete", en: "seven", pron: "SYEH-teh" },
      { es: "ocho", en: "eight", pron: "OH-choh" },
      { es: "nueve", en: "nine", pron: "NWEH-veh" },
      { es: "diez", en: "ten", pron: "dyehs" },
      { es: "once", en: "eleven", pron: "OHN-seh" },
      { es: "doce", en: "twelve", pron: "DOH-seh" },
      { es: "trece", en: "thirteen", pron: "TREH-seh" },
      { es: "catorce", en: "fourteen", pron: "kah-TOR-seh" },
      { es: "quince", en: "fifteen", pron: "KEEN-seh" },
      { es: "dieciséis", en: "sixteen", pron: "dyeh-see-SEH-ees" },
      { es: "diecisiete", en: "seventeen", pron: "dyeh-see-SYEH-teh" },
      { es: "dieciocho", en: "eighteen", pron: "dyeh-see-OH-choh" },
      { es: "diecinueve", en: "nineteen", pron: "dyeh-see-NWEH-veh" },
      { es: "veinte", en: "twenty", pron: "VAIN-teh" },
    ],
  },
  {
    id: "numbers-20-40",
    title: "Numbers 20-40",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-numbers\"></use></svg>",
    description: "Count from twenty to forty.",
    words: [
      { es: "veinte", en: "twenty", pron: "VAIN-teh" },
      { es: "veintiuno", en: "twenty-one", pron: "vain-tee-OO-noh" },
      { es: "veintidós", en: "twenty-two", pron: "vain-tee-DOHS" },
      { es: "veintitrés", en: "twenty-three", pron: "vain-tee-TREHS" },
      { es: "veinticuatro", en: "twenty-four", pron: "vain-tee-KWAH-troh" },
      { es: "veinticinco", en: "twenty-five", pron: "vain-tee-SEEN-koh" },
      { es: "veintiséis", en: "twenty-six", pron: "vain-tee-SEH-ees" },
      { es: "veintisiete", en: "twenty-seven", pron: "vain-tee-SYEH-teh" },
      { es: "veintiocho", en: "twenty-eight", pron: "vain-tee-OH-choh" },
      { es: "veintinueve", en: "twenty-nine", pron: "vain-tee-NWEH-veh" },
      { es: "treinta", en: "thirty", pron: "TRAIN-tah" },
      { es: "treinta y uno", en: "thirty-one", pron: "TRAIN-tah ee OO-noh" },
      { es: "treinta y dos", en: "thirty-two", pron: "TRAIN-tah ee DOHS" },
      { es: "treinta y tres", en: "thirty-three", pron: "TRAIN-tah ee TREHS" },
      { es: "treinta y cuatro", en: "thirty-four", pron: "TRAIN-tah ee KWAH-troh" },
      { es: "treinta y cinco", en: "thirty-five", pron: "TRAIN-tah ee SEEN-koh" },
      { es: "treinta y seis", en: "thirty-six", pron: "TRAIN-tah ee SEH-ees" },
      { es: "treinta y siete", en: "thirty-seven", pron: "TRAIN-tah ee SYEH-teh" },
      { es: "treinta y ocho", en: "thirty-eight", pron: "TRAIN-tah ee OH-choh" },
      { es: "treinta y nueve", en: "thirty-nine", pron: "TRAIN-tah ee NWEH-veh" },
      { es: "cuarenta", en: "forty", pron: "kwah-REHN-tah" },
    ],
  },
  {
    id: "numbers-40-60",
    title: "Numbers 40-60",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-numbers\"></use></svg>",
    description: "Count from forty to sixty.",
    words: [
      { es: "cuarenta", en: "forty", pron: "kwah-REHN-tah" },
      { es: "cuarenta y uno", en: "forty-one", pron: "kwah-REHN-tah ee OO-noh" },
      { es: "cuarenta y dos", en: "forty-two", pron: "kwah-REHN-tah ee DOHS" },
      { es: "cuarenta y tres", en: "forty-three", pron: "kwah-REHN-tah ee TREHS" },
      { es: "cuarenta y cuatro", en: "forty-four", pron: "kwah-REHN-tah ee KWAH-troh" },
      { es: "cuarenta y cinco", en: "forty-five", pron: "kwah-REHN-tah ee SEEN-koh" },
      { es: "cuarenta y seis", en: "forty-six", pron: "kwah-REHN-tah ee SEH-ees" },
      { es: "cuarenta y siete", en: "forty-seven", pron: "kwah-REHN-tah ee SYEH-teh" },
      { es: "cuarenta y ocho", en: "forty-eight", pron: "kwah-REHN-tah ee OH-choh" },
      { es: "cuarenta y nueve", en: "forty-nine", pron: "kwah-REHN-tah ee NWEH-veh" },
      { es: "cincuenta", en: "fifty", pron: "seen-KWEHN-tah" },
      { es: "cincuenta y uno", en: "fifty-one", pron: "seen-KWEHN-tah ee OO-noh" },
      { es: "cincuenta y dos", en: "fifty-two", pron: "seen-KWEHN-tah ee DOHS" },
      { es: "cincuenta y tres", en: "fifty-three", pron: "seen-KWEHN-tah ee TREHS" },
      { es: "cincuenta y cuatro", en: "fifty-four", pron: "seen-KWEHN-tah ee KWAH-troh" },
      { es: "cincuenta y cinco", en: "fifty-five", pron: "seen-KWEHN-tah ee SEEN-koh" },
      { es: "cincuenta y seis", en: "fifty-six", pron: "seen-KWEHN-tah ee SEH-ees" },
      { es: "cincuenta y siete", en: "fifty-seven", pron: "seen-KWEHN-tah ee SYEH-teh" },
      { es: "cincuenta y ocho", en: "fifty-eight", pron: "seen-KWEHN-tah ee OH-choh" },
      { es: "cincuenta y nueve", en: "fifty-nine", pron: "seen-KWEHN-tah ee NWEH-veh" },
      { es: "sesenta", en: "sixty", pron: "seh-SEHN-tah" },
    ],
  },
  {
    id: "numbers-60-80",
    title: "Numbers 60-80",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-numbers\"></use></svg>",
    description: "Count from sixty to eighty.",
    words: [
      { es: "sesenta", en: "sixty", pron: "seh-SEHN-tah" },
      { es: "sesenta y uno", en: "sixty-one", pron: "seh-SEHN-tah ee OO-noh" },
      { es: "sesenta y dos", en: "sixty-two", pron: "seh-SEHN-tah ee DOHS" },
      { es: "sesenta y tres", en: "sixty-three", pron: "seh-SEHN-tah ee TREHS" },
      { es: "sesenta y cuatro", en: "sixty-four", pron: "seh-SEHN-tah ee KWAH-troh" },
      { es: "sesenta y cinco", en: "sixty-five", pron: "seh-SEHN-tah ee SEEN-koh" },
      { es: "sesenta y seis", en: "sixty-six", pron: "seh-SEHN-tah ee SEH-ees" },
      { es: "sesenta y siete", en: "sixty-seven", pron: "seh-SEHN-tah ee SYEH-teh" },
      { es: "sesenta y ocho", en: "sixty-eight", pron: "seh-SEHN-tah ee OH-choh" },
      { es: "sesenta y nueve", en: "sixty-nine", pron: "seh-SEHN-tah ee NWEH-veh" },
      { es: "setenta", en: "seventy", pron: "seh-TEHN-tah" },
      { es: "setenta y uno", en: "seventy-one", pron: "seh-TEHN-tah ee OO-noh" },
      { es: "setenta y dos", en: "seventy-two", pron: "seh-TEHN-tah ee DOHS" },
      { es: "setenta y tres", en: "seventy-three", pron: "seh-TEHN-tah ee TREHS" },
      { es: "setenta y cuatro", en: "seventy-four", pron: "seh-TEHN-tah ee KWAH-troh" },
      { es: "setenta y cinco", en: "seventy-five", pron: "seh-TEHN-tah ee SEEN-koh" },
      { es: "setenta y seis", en: "seventy-six", pron: "seh-TEHN-tah ee SEH-ees" },
      { es: "setenta y siete", en: "seventy-seven", pron: "seh-TEHN-tah ee SYEH-teh" },
      { es: "setenta y ocho", en: "seventy-eight", pron: "seh-TEHN-tah ee OH-choh" },
      { es: "setenta y nueve", en: "seventy-nine", pron: "seh-TEHN-tah ee NWEH-veh" },
      { es: "ochenta", en: "eighty", pron: "oh-CHEHN-tah" },
    ],
  },
  {
    id: "numbers-80-100",
    title: "Numbers 80-100",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-numbers\"></use></svg>",
    description: "Count from eighty to one hundred.",
    words: [
      { es: "ochenta", en: "eighty", pron: "oh-CHEHN-tah" },
      { es: "ochenta y uno", en: "eighty-one", pron: "oh-CHEHN-tah ee OO-noh" },
      { es: "ochenta y dos", en: "eighty-two", pron: "oh-CHEHN-tah ee DOHS" },
      { es: "ochenta y tres", en: "eighty-three", pron: "oh-CHEHN-tah ee TREHS" },
      { es: "ochenta y cuatro", en: "eighty-four", pron: "oh-CHEHN-tah ee KWAH-troh" },
      { es: "ochenta y cinco", en: "eighty-five", pron: "oh-CHEHN-tah ee SEEN-koh" },
      { es: "ochenta y seis", en: "eighty-six", pron: "oh-CHEHN-tah ee SEH-ees" },
      { es: "ochenta y siete", en: "eighty-seven", pron: "oh-CHEHN-tah ee SYEH-teh" },
      { es: "ochenta y ocho", en: "eighty-eight", pron: "oh-CHEHN-tah ee OH-choh" },
      { es: "ochenta y nueve", en: "eighty-nine", pron: "oh-CHEHN-tah ee NWEH-veh" },
      { es: "noventa", en: "ninety", pron: "noh-VEHN-tah" },
      { es: "noventa y uno", en: "ninety-one", pron: "noh-VEHN-tah ee OO-noh" },
      { es: "noventa y dos", en: "ninety-two", pron: "noh-VEHN-tah ee DOHS" },
      { es: "noventa y tres", en: "ninety-three", pron: "noh-VEHN-tah ee TREHS" },
      { es: "noventa y cuatro", en: "ninety-four", pron: "noh-VEHN-tah ee KWAH-troh" },
      { es: "noventa y cinco", en: "ninety-five", pron: "noh-VEHN-tah ee SEEN-koh" },
      { es: "noventa y seis", en: "ninety-six", pron: "noh-VEHN-tah ee SEH-ees" },
      { es: "noventa y siete", en: "ninety-seven", pron: "noh-VEHN-tah ee SYEH-teh" },
      { es: "noventa y ocho", en: "ninety-eight", pron: "noh-VEHN-tah ee OH-choh" },
      { es: "noventa y nueve", en: "ninety-nine", pron: "noh-VEHN-tah ee NWEH-veh" },
      { es: "cien", en: "one hundred", pron: "syen" },
    ],
  },
  {
    id: "colors",
    title: "Colors",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-palette\"></use></svg>",
    description: "Describe the world around you.",
    words: [
      { es: "rojo", en: "red", pron: "ROH-hoh" },
      { es: "azul", en: "blue", pron: "ah-SOOL" },
      { es: "verde", en: "green", pron: "VER-deh" },
      { es: "amarillo", en: "yellow", pron: "ah-mah-REE-yoh" },
      { es: "naranja", en: "orange", pron: "nah-RAHN-hah" },
      { es: "morado", en: "purple", pron: "moh-RAH-doh" },
      { es: "rosa", en: "pink", pron: "ROH-sah" },
      { es: "negro", en: "black", pron: "NEH-groh" },
      { es: "blanco", en: "white", pron: "BLAHN-koh" },
      { es: "gris", en: "gray", pron: "grees" },
      { es: "marrón", en: "brown", pron: "mah-ROHN" },
    ],
  },
  {
    id: "days",
    title: "Days & Months",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-calendar\"></use></svg>",
    description: "Talk about the calendar.",
    words: [
      { es: "lunes", en: "Monday", pron: "LOO-nehs" },
      { es: "martes", en: "Tuesday", pron: "MAR-tehs" },
      { es: "miércoles", en: "Wednesday", pron: "MYEHR-koh-lehs" },
      { es: "jueves", en: "Thursday", pron: "HWEH-vehs" },
      { es: "viernes", en: "Friday", pron: "VYEHR-nehs" },
      { es: "sábado", en: "Saturday", pron: "SAH-bah-doh" },
      { es: "domingo", en: "Sunday", pron: "doh-MEEN-goh" },
      { es: "enero", en: "January", pron: "eh-NEH-roh" },
      { es: "febrero", en: "February", pron: "feh-BREH-roh" },
      { es: "marzo", en: "March", pron: "MAR-soh" },
      { es: "abril", en: "April", pron: "ah-BREEL" },
      { es: "mayo", en: "May", pron: "MAH-yoh" },
      { es: "junio", en: "June", pron: "HOO-nyoh" },
      { es: "julio", en: "July", pron: "HOO-lyoh" },
      { es: "agosto", en: "August", pron: "ah-GOHS-toh" },
      { es: "septiembre", en: "September", pron: "sep-TYEM-breh" },
      { es: "octubre", en: "October", pron: "ok-TOO-breh" },
      { es: "noviembre", en: "November", pron: "noh-VYEM-breh" },
      { es: "diciembre", en: "December", pron: "dee-SYEM-breh" },
      { es: "hoy", en: "today", pron: "oy" },
      { es: "mañana", en: "tomorrow", pron: "mah-NYAH-nah" },
      { es: "pasado mañana", en: "the day after tomorrow", pron: "pah-SAH-doh mah-NYAH-nah" },
      { es: "ayer", en: "yesterday", pron: "ah-YEHR" },
      { es: "anteayer", en: "the day before yesterday", pron: "ahn-teh-ah-YEHR" },
    ],
  },
  {
    id: "family",
    title: "Family",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-family\"></use></svg>",
    description: "Meet the family members.",
    words: [
      { es: "la familia", en: "the family", pron: "lah fah-MEE-lyah" },
      { es: "la madre", en: "mother", pron: "lah MAH-dreh" },
      { es: "el padre", en: "father", pron: "el PAH-dreh" },
      { es: "el hermano", en: "brother", pron: "el er-MAH-noh" },
      { es: "la hermana", en: "sister", pron: "lah er-MAH-nah" },
      { es: "el hijo", en: "son", pron: "el EE-hoh" },
      { es: "la hija", en: "daughter", pron: "lah EE-hah" },
      { es: "el abuelo", en: "grandfather", pron: "el ah-BWEH-loh" },
      { es: "la abuela", en: "grandmother", pron: "lah ah-BWEH-lah" },
      { es: "el esposo", en: "husband", pron: "el ehs-POH-soh" },
      { es: "la esposa", en: "wife", pron: "lah ehs-POH-sah" },
      { es: "el amigo", en: "friend (male)", pron: "el ah-MEE-goh" },
      { es: "la amiga", en: "friend (female)", pron: "lah ah-MEE-gah" },
      { es: "el tío", en: "uncle", pron: "el TEE-oh" },
      { es: "la tía", en: "aunt", pron: "lah TEE-ah" },
      { es: "el sobrino", en: "nephew", pron: "el soh-BREE-noh" },
      { es: "la sobrina", en: "niece", pron: "lah soh-BREE-nah" },
      { es: "la familia lejana", en: "distant family", pron: "lah fah-MEE-lyah leh-HAH-nah" },
      { es: "el amigo de la familia", en: "family friend (male)", pron: "el ah-MEE-goh deh lah fah-MEE-lyah" },
      { es: "la amiga de la familia", en: "family friend (female)", pron: "lah ah-MEE-gah deh lah fah-MEE-lyah" },
    ],
  },
  {
    id: "home-neighbors",
    title: "Home & Neighbors",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-house\"></use></svg>",
    description: "Talk about where you live and who's nearby.",
    words: [
      { es: "el vecino", en: "neighbor (male)", pron: "el veh-SEE-noh" },
      { es: "la vecina", en: "neighbor (female)", pron: "lah veh-SEE-nah" },
      { es: "el vecindario", en: "the neighborhood", pron: "el veh-seen-DAH-ryoh" },
      { es: "en la zona", en: "in the area", pron: "en lah SOH-nah" },
      { es: "la misma zona", en: "the same area", pron: "lah MEES-mah SOH-nah" },
      { es: "el mismo vecindario", en: "the same neighborhood", pron: "el MEES-moh veh-seen-DAH-ryoh" },
      { es: "arriba", en: "upstairs", pron: "ah-REE-bah" },
      { es: "abajo", en: "downstairs", pron: "ah-BAH-hoh" },
      { es: "el mismo piso", en: "the same floor", pron: "el MEES-moh PEE-soh" },
      { es: "el mismo apartamento", en: "the same apartment", pron: "el MEES-moh ah-par-tah-MEHN-toh" },
      { es: "vivir juntos", en: "to live together", pron: "vee-VEER HOON-tohs" },
    ],
  },
  {
    id: "questions",
    title: "Common Questions",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-question\"></use></svg>",
    description: "Ask about names, origin, and more.",
    words: [
      { es: "¿Cómo te llamas?", en: "What is your name?", pron: "KOH-moh teh YAH-mahs" },
      { es: "Me llamo...", en: "My name is...", pron: "meh YAH-moh" },
      { es: "¿De dónde eres?", en: "Where are you from?", pron: "deh DOHN-deh EH-rehs" },
      { es: "Soy de...", en: "I am from...", pron: "soy deh" },
      { es: "¿Qué hora es?", en: "What time is it?", pron: "keh OH-rah ehs" },
      { es: "¿Dónde está...?", en: "Where is...?", pron: "DOHN-deh ehs-TAH" },
      { es: "¿Cuánto cuesta?", en: "How much does it cost?", pron: "KWAN-toh KWEHS-tah" },
      { es: "¿Qué es esto?", en: "What is this?", pron: "keh ehs EHS-toh" },
      { es: "¿Puedes ayudarme?", en: "Can you help me?", pron: "PWEH-dehs ah-yoo-DAR-meh" },
      { es: "No entiendo", en: "I don't understand", pron: "noh en-TYEN-doh" },
    ],
  },
  {
    id: "food",
    title: "Food & Drink",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-food\"></use></svg>",
    description: "Order and talk about meals.",
    words: [
      { es: "el agua", en: "water", pron: "el AH-gwah" },
      { es: "el café", en: "coffee", pron: "el kah-FEH" },
      { es: "el pan", en: "bread", pron: "el pahn" },
      { es: "el queso", en: "cheese", pron: "el KEH-soh" },
      { es: "la fruta", en: "fruit", pron: "lah FROO-tah" },
      { es: "la manzana", en: "apple", pron: "lah mahn-SAH-nah" },
      { es: "el pollo", en: "chicken", pron: "el POH-yoh" },
      { es: "el arroz", en: "rice", pron: "el ah-ROHS" },
      { es: "la leche", en: "milk", pron: "lah LEH-cheh" },
      { es: "el desayuno", en: "breakfast", pron: "el deh-sah-YOO-noh" },
      { es: "el almuerzo", en: "lunch", pron: "el ahl-MWEHR-soh" },
      { es: "la cena", en: "dinner", pron: "lah SEH-nah" },
      { es: "Tengo hambre", en: "I am hungry", pron: "TEHN-goh AHM-breh" },
      { es: "Tengo sed", en: "I am thirsty", pron: "TEHN-goh sehd" },
    ],
  },
  {
    id: "kitchen",
    title: "Kitchen",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-kitchen\"></use></svg>",
    description: "Name everything you'll find in the kitchen.",
    words: [
      { es: "la cocina", en: "the kitchen", pron: "lah koh-SEE-nah" },
      { es: "el plato", en: "plate", pron: "el PLAH-toh" },
      { es: "el tazón", en: "bowl", pron: "el tah-SOHN" },
      { es: "la cuchara", en: "spoon", pron: "lah koo-CHAH-rah" },
      { es: "el tenedor", en: "fork", pron: "el teh-neh-DOR" },
      { es: "el cuchillo", en: "knife", pron: "el koo-CHEE-yoh" },
      { es: "la taza", en: "cup / mug", pron: "lah TAH-sah" },
      { es: "la taza de té", en: "tea cup", pron: "lah TAH-sah deh teh" },
      { es: "el vaso", en: "glass / water cup", pron: "el VAH-soh" },
      { es: "la olla", en: "pot", pron: "lah OH-yah" },
      { es: "la sartén", en: "pan", pron: "lah sar-TEN" },
      { es: "la estufa", en: "stove", pron: "lah ehs-TOO-fah" },
      { es: "el horno", en: "oven", pron: "el OR-noh" },
      { es: "el refrigerador", en: "fridge", pron: "el reh-free-heh-rah-DOR" },
      { es: "el fregadero", en: "sink", pron: "el freh-gah-DEH-roh" },
      { es: "el lavavajillas", en: "dishwasher", pron: "el lah-vah-vah-HEE-yahs" },
      { es: "el microondas", en: "microwave", pron: "el mee-kroh-OHN-dahs" },
      { es: "la cafetera", en: "coffee machine", pron: "lah kah-feh-TEH-rah" },
      { es: "la espátula", en: "spatula", pron: "lah ehs-PAH-too-lah" },
      { es: "el cucharón", en: "ladle", pron: "el koo-chah-ROHN" },
      { es: "el abrelatas", en: "can opener", pron: "el ah-breh-LAH-tahs" },
      { es: "la tabla de cortar", en: "cutting board", pron: "lah TAH-blah deh kor-TAR" },
      { es: "el colador", en: "strainer / colander", pron: "el koh-lah-DOR" },
      { es: "el batidor", en: "whisk", pron: "el bah-tee-DOR" },
      { es: "el rodillo", en: "rolling pin", pron: "el roh-DEE-yoh" },
      { es: "la tostadora", en: "toaster", pron: "lah tohs-tah-DOH-rah" },
      { es: "el hervidor", en: "kettle", pron: "el er-vee-DOR" },
      { es: "la licuadora", en: "blender", pron: "lah lee-kwah-DOH-rah" },
      { es: "el cajón", en: "drawer", pron: "el kah-HOHN" },
      { es: "el gabinete", en: "cabinet", pron: "el gah-bee-NEH-teh" },
      { es: "la encimera", en: "countertop", pron: "lah en-see-MEH-rah" },
      { es: "la despensa", en: "pantry", pron: "lah dehs-PEHN-sah" },
      { es: "la tapa", en: "lid", pron: "lah TAH-pah" },
      { es: "los guantes de cocina", en: "oven mitts", pron: "lohs GWAHN-tehs deh koh-SEE-nah" },
      { es: "el paño de cocina", en: "kitchen towel", pron: "el PAH-nyoh deh koh-SEE-nah" },
      { es: "el delantal", en: "apron", pron: "el deh-lahn-TAHL" },
      { es: "la esponja", en: "sponge", pron: "lah ehs-POHN-hah" },
      { es: "el jabón para platos", en: "dish soap", pron: "el hah-BOHN PAH-rah PLAH-tohs" },
      { es: "el bote de basura", en: "trash can", pron: "el BOH-teh deh bah-SOO-rah" },
      { es: "la servilleta", en: "napkin", pron: "lah ser-vee-YEH-tah" },
      { es: "el mantel", en: "tablecloth", pron: "el mahn-TEL" },
      { es: "las toallas de papel", en: "paper towels", pron: "lahs toh-AH-yahs deh pah-PEL" },
    ],
  },
  {
    id: "verbs",
    title: "Ser vs. Estar",
    icon: "<svg class=\"icon-svg\" aria-hidden=\"true\"><use href=\"#icon-verbs\"></use></svg>",
    description: "The two verbs for 'to be' (present tense).",
    words: [
      { es: "yo soy", en: "I am (ser - identity)", pron: "yoh soy" },
      { es: "tú eres", en: "you are (ser - identity)", pron: "too EH-rehs" },
      { es: "él/ella es", en: "he/she is (ser - identity)", pron: "el EH-yah ehs" },
      { es: "nosotros somos", en: "we are (ser - identity)", pron: "noh-SOH-trohs SOH-mohs" },
      { es: "yo estoy", en: "I am (estar - state/location)", pron: "yoh ehs-TOY" },
      { es: "tú estás", en: "you are (estar - state/location)", pron: "too ehs-TAHS" },
      { es: "él/ella está", en: "he/she is (estar - state/location)", pron: "el EH-yah ehs-TAH" },
      { es: "nosotros estamos", en: "we are (estar - state/location)", pron: "noh-SOH-trohs ehs-TAH-mohs" },
      { es: "Soy alto", en: "I am tall (permanent trait)", pron: "soy AHL-toh" },
      { es: "Estoy cansado", en: "I am tired (temporary state)", pron: "ehs-TOY kahn-SAH-doh" },
    ],
  },
];
